export const GET_ALL_ENGRAVING_ORDERS_REQUEST = "GET_ALL_ENGRAVING_ORDERS_REQUEST";
export const GET_ALL_ENGRAVING_ORDERS_SUCCESS = "GET_ALL_ENGRAVING_ORDERS_SUCCESS";
export const GET_ALL_ENGRAVING_ORDERS_FAILURE = "GET_ALL_ENGRAVING_ORDERS_FAILURE";